# Generated by Django 4.2 on 2023-05-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
