# Generated by Django 4.2 on 2023-05-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('links', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('contributers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributersx', to='friends.friends')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagsx', to='projectlist.tags')),
            ],
        ),
    ]
