# Generated by Django 4.2 on 2023-05-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        ('projectlist', '0002_remove_projects_tags_projects_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='contributers',
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='links',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='contributers',
            field=models.ManyToManyField(to='friends.friends'),
        ),
    ]
